### ISSUE TITLE
Can I provide multiple directories or do a recursive search for a matching directory?

### ISSUE THREAD

**Issue by sheldonhull** [patrickjahns/dependabot-terraform-action#17]
I'm stoked to use this! 
I wanted to ask about being able to specific a root directory and have it look for versions.tf directories. Is this possible. 
I don't write Ruby, but in reading the code it seems it expects a single directory right now?

I don't think this should work right?
```yaml
- uses: patrickjahns/depedanbot-terraform-action@v1
  with:
    directory:
      - 'plans/prod/foo'
      - 'plans/prod/terraform-cloud-workspaces'
      - 'plans/qa/bar'
      - 'plans/qa/terraform-cloud-workspaces'
```

So if this is the case, maybe I could request if it's easy, 2 things. 
1. Possible to offer match pattern so any folder with `versions.tf` or maybe even `main.tf` could be evaluated in a directory collection and then each parsed?
2. If that's too complex for a quick solution, possibility to support input of string list so I can provide each plan directory to search

The main reason I wanted to leverage this is to simplify bumping the version on a plan repo that will continue to grow and need me to occasionally bump the version of providers. Until dependabot handles this, maybe your github action will provide that better fix!

Thanks again for throwing this together. Much appreciated!

**Comment by sheldonhull** [comment]
In the meantime, not ideal but I think I found a work around for now. 

```yml
name: Update terraform dependencies
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron:  '00 10 * * mon'  # At 10:00 on Monday.   https://crontab.guru/#00_10_*_*_mon
strategy:
  matrix:
    directory:
      - 'plans/prod/foobar'
      - 'plans/prod/terraform-cloud-workspaces'
      - 'plans/qa/taco'
      - 'plans/qa/terraform-cloud-workspaces'
jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update terraform dependencies
        uses: patrickjahns/dependabot-terraform-action@v1
        with:
          github_dependency_token: ${{ secrets.DEPENDENCY_GITHUB_TOKEN }}
          token: '${{ github.token }}'
          directory: '${{ matrix.directory }}'

```

I think the matrix functionality will allow me to spin off one of your github actions for each directory input provided. 
Maybe you'll find a better way to build it into the action yourself, but in the meantime I'll take a swing at using this.
