### ISSUE TITLE
Running action doesn't bump provider versions in modules

### ISSUE THREAD

**Issue by tobiasehlert** [patrickjahns/dependabot-terraform-action#46]
I don't really get, why the providers aren't updated in my modules.

This is basically how my action is looking:

```yaml
name: Update terraform dependencies
on:
  workflow_dispatch:
jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: patrickjahns/dependabot-terraform-action@v1
        with:
          target_branch: master
          token: ${{ secrets.PAT_TOKEN }}
          directory: |
            /modules/gcp_folder
            /modules/gcp_iam_role
            /modules/gcp_log_sink
```

The output of the action is this:

```plain
  - Checking /modules/gcp_folder ...
  - Parsing dependencies information
  - Checking /modules/gcp_iam_role ...
  - Parsing dependencies information
  - Checking /modules/gcp_log_sink ...
  - Parsing dependencies information
  - Done
```

There is nothing happening when it's completed and there is no PR created. The output doesn't state anything either.. so hot can I see if it's failing or is it possible to get a more detailed information when running like "found version XX".
I've added different versions in the providers so it should have triggered on some..
